package helloapp;

/**
* helloapp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Saturday, February 22, 2014 12:08:39 AM CST
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public helloapp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (helloapp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = helloapp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    helloapp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return helloapp.HelloHelper.type ();
  }

}
