
/**
* ABCExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from abc.idl
* Saturday, February 22, 2014 11:37:14 PM CST
*/

public final class ABCExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public ABCException value = null;

  public ABCExceptionHolder ()
  {
  }

  public ABCExceptionHolder (ABCException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ABCExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ABCExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ABCExceptionHelper.type ();
  }

}
