#!/bin/bash
#set -o xtrace
_dbname=${0##*/} #equal to basename

if (($#<1)) ; then
   echo "$_dbname: Usage: $_dbnam filename" >&2
   exit 1
fi

_gunieapig="$PWD/$1"

if [ ! -r $1 ]; then
   echo "$_dbname: Cannot read file '$_guineapig'." >&2
   exit 1
fi

shift

_tmpdir=/tmp
_libdir=${PWD}
_debugfile=$_tmpdir/bashdb.$$

cat $_libdir/bashdb.pre $_gunieapig > $_debugfile
exec bash $_debugfile $_gunieapig $_tmpdir $_libdir "$@"
