#!/bin/bash
_dbname=${0##*/} #equal to basename

if (($#<1)) ; then
	echo "$_dbname: Usage: $_dbnam filename" >&2
	exit 1
fi

_guineapig=$1

if [ ! -r $1 ]; then
	echo "$_dbname: Cannot read file '$_guineapig'." >&2
	exit 1
fi

shift

_tmpdir=/tmp
_libdir=.
_debugfile=$_tmpdir/bashdb.$$

cat $_libdir/bashdb.pre $_gunieapig > $_debugfile
exec bash $_debugfile $_guineapig $_tmpdir $_libdir "$@"
