.PHONY: dummy

dummy:
	@echo $(MAKE_VERSION)
	@echo $(CURDIR)
	@echo "$(.VARIABLES)"
	@echo $(COMPILE.C)
	@echo $(CXX)
	@echo $(CXXFLAGS)
	@echo $(TARGET_ARCH)

default: pre pre2 pre2
	@echo $+
	@echo $<
	@echo $^
	@echo $@
	@echo $?
