package helloapp;

/**
* helloapp/ABCHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from abc.idl
* Saturday, February 22, 2014 11:37:14 PM CST
*/

public final class ABCHolder implements org.omg.CORBA.portable.Streamable
{
  public helloapp.ABC value = null;

  public ABCHolder ()
  {
  }

  public ABCHolder (helloapp.ABC initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = helloapp.ABCHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    helloapp.ABCHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return helloapp.ABCHelper.type ();
  }

}
