package helloapp;


/**
* helloapp/ABCHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from abc.idl
* Saturday, February 22, 2014 11:37:14 PM CST
*/

abstract public class ABCHelper
{
  private static String  _id = "IDL:helloapp/ABC:1.0";

  public static void insert (org.omg.CORBA.Any a, helloapp.ABC that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static helloapp.ABC extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (helloapp.ABCHelper.id (), "ABC");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static helloapp.ABC read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ABCStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, helloapp.ABC value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static helloapp.ABC narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof helloapp.ABC)
      return (helloapp.ABC)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      helloapp._ABCStub stub = new helloapp._ABCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static helloapp.ABC unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof helloapp.ABC)
      return (helloapp.ABC)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      helloapp._ABCStub stub = new helloapp._ABCStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
