package helloapp;

import ABCException;
import ABCExceptionHelper;

/**
* helloapp/ABCOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from abc.idl
* Saturday, February 22, 2014 11:37:14 PM CST
*/

public interface ABCOperations 
{
  void abc () throws ABCException;
} // interface ABCOperations
