guess: guess-my-number.cli
	clisp -i guess-my-number.cli

my-length: my-length.cli
	clisp -i my-length.cli

when: when.cli
	clisp -i when.cli

cond: cond.cli
	clisp -i cond.cli

case: case.cli
	clisp -i case.cli

clean:
	rm -rf *.*~ *~

.PHONY: clean
