/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Happy */

#ifndef _Included_Happy
#define _Included_Happy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Happy
 * Method:    printText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Happy_printText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
