// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

public final class RMIDemoImpl_Stub
    extends java.rmi.server.RemoteStub
    implements RMIDemo, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_doCommunicate_0;
    
    static {
	try {
	    $method_doCommunicate_0 = RMIDemo.class.getMethod("doCommunicate", new java.lang.Class[] {java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RMIDemoImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of doCommunicate(String)
    public java.lang.String doCommunicate(java.lang.String $param_String_1)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_doCommunicate_0, new java.lang.Object[] {$param_String_1}, -3636068691756674796L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
