package StockMarket;


/**
* StockMarket/StockServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StockMarket.idl
* Wednesday, February 19, 2014 2:26:41 AM CST
*/

public abstract class StockServerPOA extends org.omg.PortableServer.Servant
 implements StockMarket.StockServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getStockValue", new java.lang.Integer (0));
    _methods.put ("getStockSymbols", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // StockMarket/StockServer/getStockValue
       {
         String symbol = StockMarket.StockSymbolHelper.read (in);
         float $result = (float)0;
         $result = this.getStockValue (symbol);
         out = $rh.createReply();
         out.write_float ($result);
         break;
       }

       case 1:  // StockMarket/StockServer/getStockSymbols
       {
         String $result[] = null;
         $result = this.getStockSymbols ();
         out = $rh.createReply();
         StockMarket.StockSymbolListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StockMarket/StockServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public StockServer _this() 
  {
    return StockServerHelper.narrow(
    super._this_object());
  }

  public StockServer _this(org.omg.CORBA.ORB orb) 
  {
    return StockServerHelper.narrow(
    super._this_object(orb));
  }


} // class StockServerPOA
