module StockMarket {
  typedef string StockSymbol;
  typedef sequence<StockSymbol> StockSymbolList;
  
  interface StockServer {
    float getStockValue(in StockSymbol symbol);
    StockSymbolList getStockSymbols();
  };
};


