#!/bin/sh

# shpell - An interactive spell-checking program that lets you step
#   through all known spelling errors in a document, indicate which
#   ones you'd like to fix and how, and apply the changes to the file
#   The original version of the file is saved with a .orig suffix,
#   and the new version replaces the old.
#
# Note that you need a standard 'spell' command for this to work, which
# might involve installing aspell, ispell, or pspell on your system.

tempfile="/tmp/$(basename $0).$$"
changerequests="/tmp/$(basename $0).$$.sed"
spell="ispell -l"                # modify as needed for your own spell

trap "rm -f $tempfile $changerequests" EXIT HUP INT QUIT TERM

# Include the ansi color sequence definitions

. library
initializeANSI

getfix()
{
# Asks the user to specify a correction. If the user enters a replacement word
# that's also misspelled, the function calls itself, which is a level 2 nesting.
# This can go as deep as the user might need, but keeping track of nesting enables
# us to ensure that only level 1 outputs the "replacing word" message.

  word=$1
  filename=$2
  misspelled=1

  while [ $misspelled -eq 1 ]
  do

    echo ""; echo "${boldon}Misspelled word ${word}:${boldoff}"
    grep -n $word $filename |
        sed -e 's/^/   /' -e "s/$word/$boldon$word$boldoff/g"
    echon "i)gnore, q)uit, or type replacement: "
    read fix
    if [ "$fix" = "q" -o "$fix" = "quit" ] ; then
      echo "Exiting without applying any fixes."; exit 0
    elif [ "${fix%${fix#?}}" = "!" ] ; then
      misspelled=0    # user forcing replacement, stop checking
      echo "s/$word/${fix#?}/g" >> $changerequests
    elif [ "$fix" = "i" -o -z "$fix" ] ; then
      misspelled=0
    else
      if [ ! -z "$(echo $fix | sed 's/[^ ]//g')" ] ; then
        misspelled=0    # once we see spaces, we stop checking
        echo "s/$word/$fix/g" >> $changerequests
      else
        # It's a single-word replacement, let's spell-check the replacement too
        if [ ! -z "$(echo $fix | $spell)" ] ; then
          echo ""
          echo "*** Your suggested replacement $fix is misspelled."
          echo "*** Preface the word with '!' to force acceptance."
        else
          misspelled=0  # suggested replacement word is acceptable
          echo "s/$word/$fix/g" >> $changerequests
        fi
      fi
    fi
  done
}

### Beginning of actual script body
if [ $# -lt 1 ] ; then
  echo "Usage: $0 filename" >&2 ; exit 1
fi

if [ ! -r $1 ] ; then
  echo "$0: Cannot read file $1 to check spelling" >&2 ; exit 1
fi

# Note that the following invocation fills $tempfile along the way
errors="$($spell < $1 | tee $tempfile | wc -l | sed 's/[^[:digit:]]//g')"

if [ $errors -eq 0 ] ; then
  echo "There are no spelling errors in $1."; exit 0
fi

echo "We need to fix $errors misspellings in the document. Remember that the"
echo "default answer to the spelling prompt is 'ignore', if you're lazy."
touch $changerequests

for word in $(cat $tempfile)
do
  getfix $word $1 1
done

if [ $(wc -l < $changerequests) -gt 0 ] ; then
  sed -f $changerequests $1 > $1.new
  mv $1 $1.orig
  mv $1.new $1
  echo Done. Made $(wc -l < $changerequests) changes.
fi

exit 0
